### ISSUE TITLE
Immediate crash

### ISSUE THREAD

**Issue by Arch23-tech** [WIX3Y/additional-fishing#2]
Before anything I like to thank you for your efforts as updating the mod 

I'm currently using (Fabric - minecraft 1.20.1)  for some unknown reason whenever I launch minecraft with the new version (Additional fishing 1.1.0) it immediately crashes.  
The previous version worked fine and very smoothly but the newer version keeps crashing the launching process immediately...

**Comment by WIX3Y** [comment]
Hello, in order for me to assist, please provide fabric loader version, mod list and error logs

**Comment by Arch23-tech** [comment]
This is the log file 
[latest.log](https://github.com/user-attachments/files/16504743/latest.log)

**Comment by WIX3Y** [comment]
From what I can see in your logs, you are using forge with some sort of fabric-to-forge translation mod? This is sadly not something I can guarantee support for.
